### ISSUE TITLE
Investigate Authorizing Environments and Queues

### ISSUE THREAD

**Issue by plooploops** [microsoft/OHDSIonAzure#13]
- Investigate authorizing ADO environments and ADO queues
  - these are currently not included in the [Azure DevOps TF provider](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs), currently using script as a workaround.

**Comment by yradsmikham** [comment]
@plooploops can you elaborate what you mean by "authorizing"? Is there a parameter in TF we can use?

**Comment by plooploops** [comment]
Currently we are using these TF modules to authorize the Agent Pools (queues) and Azure DevOps environments:
* [azure_devops_elastic_pool_pipeline_assignment](https://github.com/microsoft/OHDSIonAzure/tree/main/infra/terraform/modules/azure_devops_elastic_pool_pipeline_assignment)

```diff
module "azure_devops_elastic_pool_for_pipeline_assignment" {
  source              = "modules/azure_devops_elastic_pool_pipeline_assignment"
+ authorized          = true
  ado_org_service_url = "https://dev.azure.com/my-org/"
  ado_pat             = "my-ado-pat"
  ado_project_name    = "my-ado-project"
  ado_queue_id        = 3 # assuming you have setup your Azure DevOps VMSS Agent Pool and its id is 3 
  ado_pipeline_id     = 5 # Assuming you have setup a build definition 
}
```

* [azure_devops_environment_pipeline_assignment](https://github.com/microsoft/OHDSIonAzure/tree/main/infra/terraform/modules/azure_devops_environment_pipeline_assignment)

```diff
module "azure_devops_environment_tf_plan_pipeline_assignment" {
  source              = "modules/azure_devops_environment_pipeline_assignment"
+  authorized          = true
  ado_org_service_url = "https://dev.azure.com/my-org/"
  ado_pat             = "my-ado-pat"
  ado_project_name    = "my-ado-project"
  ado_environment_id  = 3 # Assuming you have your ADO Environment and its id is 3
  ado_pipeline_id     = 5 # Assuming you have setup a build definition 
}
```

Setting `authorized` to `true` will let the specified Azure DevOps pipeline use the Azure DevOps Queue (Agent Pool) and the Azure DevOps Environment
