### ISSUE TITLE
Investigate automating backend state settings for local development

### ISSUE THREAD

**Issue by plooploops** [microsoft/OHDSIonAzure#14]
- The bootstrap TF sets up an Azure Blob Storage account and container for the omop TF.
  - Investigate if there's a way to include passing the storage account settings into the omop TF workspace (for now, this assumes that the same person is running both the bootstrap TF project and omop TF project)
  - [Store Terraform state in Azure Storage | Microsoft Docs](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli), this is handled through `terraform init` once you have configured your backend

**Comment by yradsmikham** [comment]
Discussed with @plooploops on the following approach:

- Refactor bootstrap TF to add variables in omop env VG that will inclued 
- Refactor TF-OMOP.yaml to include environment variable for `ARM_ACCESS_KEY` for storage account key

The goal is to streamline infrastructure setup for the end user. This will remove the manual steps of initializing backend tf state file in Storage Account, editing the OMOP environment TF variables file, and setting environment variables.
