### ISSUE TITLE
Diagnostic settings does not support retention for new diagnostic settings.

### ISSUE THREAD

**Issue by e86h90** [microsoft/OHDSIonAzure#167]
There are several instances of setting retention days for Diagnostics in main.bicep.

   logs: [
      {
        category: 'AuditEvent'
        enabled: true
        retentionPolicy: {
          days: 30
          enabled: true
      }

This is no longer supported and results in an error:

Diagnostic settings does not support retention for new diagnostic settings. (Code: BadRequest, Target: ....

Reference: learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy

The Deployment does not complete as a result.

**Comment by Zachary-Higgins** [comment]
Is Microsoft still maintaining this repository? Looks like it's been quite a while since this issue has been reported.
