### ISSUE TITLE
Investigate using forked github repos versus importing repo into Azure DevOps

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/OHDSIonAzure#29]
- Come up with pros and cons for each approach
- Gather feedback from team and test users

**Should we allow the flexibility to have both options? Or stick to one approach for simplicity?**

If using forked repos in Github:
- Remove the need to import repos and have them be in sync in two different places (AzDo and GitHub)
- User will still need to manage forked repos and ensure that it is fetching from official `microsoft/OHDSIonAzure` repo (i.e. `git fetch`)
- Update `bootstrap/azure_devops_build_definitions.tf` `repository` block:

```repository {
    repo_type   = "GitHub"
    repo_id     = "yradsmikham/OHDSIonAzure"
    branch_name = "main"
    yml_path    = "pipelines/environments/TF-OMOP.yaml"
    service_connection_id = "<service-connection-id>"
  }
```
- Refactor pipeline yaml files to refer to forked repo (?)

If importing repos into Azure DevOps:
- Stick to current design
- User will still need to manage forked repos and ensure that it is fetching from official `microsoft/OHDSIonAzure` repo (i.e. `git fetch`)

**Comment by plooploops** [comment]
Sounds like both options are viable, so let's turn this into a documentation effort to account for it.
