### ISSUE TITLE
No sound for videos on set up page

### ISSUE THREAD

**Issue by NACHC-CAD** [microsoft/OHDSIonAzure#52]
The videos on this page don't seem to have audio.  
https://github.com/microsoft/OHDSIonAzure/blob/main/docs/creating_your_environment.md

**Comment by plooploops** [comment]
@NACHC-CAD - Thanks for reviewing the notes.

Earlier when we had put together the videos we noted that audio wouldn't be included: #31.

What type of audio would be helpful?  Would narration be something that's useful for you?

**Comment by NACHC-CAD** [comment]
Naration would be helpful.  I'm coming into this from zero.  I've been on AWS previously for other general hosting purposes. I'm looking at this from the perspective of someone that has zero Azure experience and zero OHDSI experience.

**Comment by plooploops** [comment]
@NACHC-CAD - the videos should be updated now per #56.

If you find other details need to be added or revisited, we can re-open this issue (or feel free to pop in a new one too!)
