### ISSUE TITLE
Investigate options for automating vocabulary versioning

### ISSUE THREAD

**Issue by yradsmikham** [microsoft/OHDSIonAzure#6]
Option: https://docs.pachyderm.com/latest/concepts/data-concepts/repo/

**Comment by yradsmikham** [comment]
@plooploops, what is your recommendation for this issue? You discussed that we can just create a storage account and upload vocabulary files, correct? Would this be a stationary storage account?

**Comment by plooploops** [comment]
For now, we can have a public read-only Azure Storage account with the vocabulary files.

This approach is included as part of #68
