### ISSUE TITLE
Package python-dev is not available anymore - Build and Release broadsea-methods.

### ISSUE THREAD

**Issue by migldasilva** [microsoft/OHDSIonAzure#87]
During execution of the pipeline _Build and Release broadsea-methods_, `python-dev` is supposed to be installed (this is what we have in the Dockerfile for this app, in the main branch).

The pipeline breaks giving that this package is not available anymore:

> Package python-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   python2-dev python2 python-dev-is-python3
> 
> E: Package 'python-dev' has no installation candidate

I have successfully installed packages `python2-dev` and `python-dev-is-python3`. Package `python2 `is already installed.

The pipeline proceeded correctly after such packages were installed.

**Comment by dsfrederic** [comment]
Same issue here

**Comment by tamirkamara** [comment]
A new version of this quick-start has been merged to main. Please have a look there.
