### ISSUE TITLE
OpenID not shown as authentication option

### ISSUE THREAD

**Issue by migldasilva** [microsoft/OHDSIonAzure#91]
Hi!

I've been trying to enable OpenID as an authentication provider. OpenID is provided by Azure, and I have created an Application Registration. I've added the following fields to the `app_settings` array (this array is located in the `main.tf` file, under the configurations belonging to the WebAPI's App Service):

```
"security.oid.clientId" = "<AZURE_OPENID_KEY>"
"security.oid.apiSecret"="<AZURE_OPENID_SECRET>"
"security.oid.url" = "<AZURE_OPENID_URL>"
"security.oid.redirectUrl" = "<ATLAS_FRONTPAGE_URL>"

```

Besides that, the OpenID provider has been added in the `config-loca.js` file:

```
{
  "name": "OpenID",
  "url": "user/login/openid",
  "ajax": false,
  "icon": "fab fa-openid"
}
```

Together with the OpenID, the DB authenticator is used (this authenticator works great). The problem is that only the DB authenticator is shown on the login window. Atlas loads with no problem, and when I click on Signin link, a popup shows up displaying only the DB authenticator.

So, any suggestions? :)

**Comment by tamirkamara** [comment]
This is no longer an option in this quick start (although we do plan to offer it in the future).
In the meantime you can try to learn from the link below how to make this option work:
https://github.com/microsoft/AzureTRE/pull/3562
